namespace: ha
targetCustomizations: 
- name: d-eur-pop-rke
  helm: 
    values: 
      replicas: 3
    force: true
  clusterSelector: 
    matchLabels: 
      provider.cattle.io: rke      
- name: d-eur-pop-eks
  helm: 
    values: 
      replicas: 1
    force: true
  clusterSelector: 
    matchLabels: 
      zone_name: eks


