namespace: ha
targetCustomizations: 
- name: d-eur-pop-rke
  helm: 
    values: 
      replicas: 3
  clusterSelector: 
    matchLabels: 
      zone_name: rke      
- name: d-eur-pop-eks
  helm: 
    values: 
      replicas: 1
  clusterSelector: 
    matchLabels: 
      zone_name: eks


